config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resource :welcome, only: [:index]

  resources :books, only: [:new, :index, :show, :create, :destroy] do
    resources :reviews, shallow: true, only: [:new, :create, :destroy]
  end
  resources :users, only: [:show]
  resources :authors, only: [:new, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :book_authors, :dependent => :destroy
  has_many :books, through: :book_authors


  def self.clean_me_up(params)
    author_names = params[:authors].split(', ')
    fixed_params = author_names.map do |author|
      cleaned_name = author.downcase.titlecase
      Author.find_or_create_by(name: cleaned_name)
    end
    params[:title] = params[:title].downcase.titlecase
    params[:authors] = fixed_params
    params
  end
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, uniqueness: true, presence: true
  validates_presence_of :pages
  validates_presence_of :published_year
  has_many :reviews, :dependent => :destroy
  has_many :book_authors, :dependent => :destroy
  has_many :authors, through: :book_authors

  def average_review_score
    reviews.average(:rating).to_f
  end

  def self.books_by_reviews(limit = Book.count, order)
    Book.joins(:reviews)
      .select("books.*, avg(reviews.rating) as average_rating")
      .group(:id)
      .order("average_rating #{order}")
      .limit(limit)
  end

  def top_review
    reviews.order(rating: :desc).first
  end

  def top_three_reviews
    reviews.order(rating: :desc).limit(3)
  end

  def bottom_three_reviews
    reviews.order(rating: :asc).limit(3)
  end

  def total_reviews
    reviews.count
  end

  def self.books_by_review_count(order)
    Book.joins(:reviews)
      .select("books.*, count(reviews) as total_reviews")
      .group(:id)
      .order("total_reviews #{order}")
  end

  def self.sort(sort_param, order)
    if sort_param == "pages"
      Book.order("#{sort_param} #{order}")

    elsif sort_param == "ratings"
      Book.books_by_reviews(order)

    elsif sort_param == "reviews"
      Book.books_by_review_count(order)
    end
  end
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/review.rb
class Review < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :rating
  belongs_to :user
  belongs_to :book

  def user_name(user_id)
    Review.distinct
    .joins(:user)
    .where(user_id: user_id)
    .pluck(:name)
    .first
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name, uniqueness: true
  has_many :reviews

  def self.users_by_review_count(limit)
    User.joins(:reviews)
      .select("users.*, count(reviews.id) as review_count")
      .group(:id)
      .order("review_count DESC")
      .limit(limit)
  end

  def sort_user_reviews_by_creation_date(order)
    reviews.order("created_at #{order}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    it_exists = Author.find_by(id: params[:id])
    if it_exists
      @author = Author.find(params[:id])
    else
      redirect_to books_path
    end
  end

  def destroy
    author = Author.find(params[:id])
    books = author.books
    books.each do |book|
      book.destroy
    end
    author.destroy
    redirect_to books_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @top_books = Book.books_by_reviews(3, "DESC")
    @lowest_books = Book.books_by_reviews(3, "ASC")
    @power_users = User.users_by_review_count(3)

    if params[:sort] == "reviews"
      if params[:order] == "asc"
        @books = Book.sort("reviews", "ASC")
      elsif params[:order] == "desc"
        @books = Book.sort("reviews", "DESC")
      end
    elsif params[:sort] == "ratings"
      if params[:order] == "asc"
        @books = Book.sort("ratings", "ASC")
      elsif params[:order] == "desc"
        @books = Book.sort("ratings", "DESC")
      end
    elsif params[:sort] == "pages"
      if params[:order] == "asc"
        @books = Book.sort("pages", "ASC")
      elsif params[:order] == "desc"
        @books = Book.sort("pages", "DESC")
      end
    end
  end

  def show
    it_exists = Book.find_by(id: params[:id])
    if it_exists
      @book = Book.find(params[:id])
    else
      redirect_to books_path
    end
  end

  def new
    @book = Book.new
  end

  def create
    adjusted_params = Author.clean_me_up(book_params)
    @book = Book.create(adjusted_params)
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :pages, :published_year, :authors)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @book = Book.find(params[:book_id])
    @review = Review.new
  end

  def create
    book = Book.find(params[:book_id])
    user = User.find_or_create_by(name: review_params[:user])
    complete_params = review_params
    complete_params[:book_id] = book.id
    complete_params[:user] = user
    title = review_params[:title]
    description = review_params[:description]
    rating = review_params[:rating]
    review_user = User.find_or_create_by(name: review_params[:user].downcase.titlecase)
    Review.create(title: title, description: description, rating: rating, user: review_user, book: book)
    redirect_to book_path(book)
  end

  def destroy
    review = Review.find(params[:id])
    user = review.user
    review.destroy
    redirect_to user_path(user)
  end

  private

  def review_params
    params.require(:review).permit(:title, :rating, :description, :user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    it_exists = User.find_by(id: params[:id])
    if it_exists
      @user = User.find(params[:id])
      if params[:sort] == "reviewsdate"
        if params[:order] == "asc"
          @reviews = @user.sort_user_reviews_by_creation_date("ASC")
        elsif params[:order] == "desc"
          @reviews = @user.sort_user_reviews_by_creation_date("DESC")
        end
      else
        @reviews = @user.reviews
      end
    else
      redirect_to books_path
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/show.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="/stylesheets/author_show.css">
</head>
<body>

<h1>Author SHOW</h1>

<%= link_to "Delete Author", author_path(@author), method: :delete %>
<div id="author-information">
  <%= @author.name %>
  <div class="row">
  <% @author.books.each do |book| %>
  <div class="column column-<%=book.id%>">
    <h2 class="book-title"><%= link_to book.title, book_path(book.id) %></h2><br>
      <p><%= book.pages %></p>
      <p><%= book.published_year %></p>
      <% if book.authors.length > 1 %>
        <% book.authors.each do |author|%>
        <% unless author == @author %>
        <h2 class="coauthors-names"><%= link_to author.name, author_path(author.id) %></h2>
        <%end%>
        <%end%>
      <%end%>
      <div id="book-review">
        <% if book.top_review %>
          <p><%= book.top_review.title %></p>
          <p><%= link_to book.top_review.user_name(book.top_review.user_id), user_path(book.top_review.user_id)  %></p>
          <p><%= book.top_review.rating %></p>
          <p><%= book.top_review.description %></p>
          <% end %>
      </div>
      </div>
  <% end %>
</div>
</div>

</body>

app/views/books/index.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="/stylesheets/book_index.css">
  <title>Athenaeum</title>
</head>

<div id="statistics">
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Athenaeum</h1>
    <a href="/books/new" id="Add Book"class="badge badge-secondary">Add Book</a>
    <p class="lead">
      <article class="book-stats">
        <div class="top-books">
          <h2>TOP BOOKS:</h2>
          <% @top_books.each do |book| %>
            <p><%= link_to book.title, book_path(book.id) %> - <%= book.average_rating.round %> <i class="fas fa-star"></i></p>
          <% end %>
        </div>
      </article>
      <article class="book-stats">
        <div class="lowest-books">
          <h2>LOWEST RATED BOOKS:</h2>
          <% @lowest_books.each do |book|%>
            <p><%= link_to book.title, book_path(book.id) %> - <%= book.average_rating.round %> <i class="fas fa-star"></i></p>
          <% end %>
        </div>
      </article>
      <article class="book-stats">
        <div class="top-users">
          <h2>TOP POWER USERS:</h2>
          <% @power_users.each do |user| %>
            <p><%= link_to user.name, user_path(user.id) %> - <%= user.review_count %> reviews!</p>
          <% end %>
        </div>
      </article>
    <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Sort by:
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" id="reviews-asc" href="?sort=reviews&order=asc">Review Count: Ascending</a>
      <a class="dropdown-item" id="reviews-desc" href="?sort=reviews&order=desc">Review Count: Descending</a>
      <a class="dropdown-item" id="ratings-asc" href="?sort=ratings&order=asc">Avg Rating: Ascending</a>
      <a class="dropdown-item" id="ratings-desc" href="?sort=ratings&order=desc">Avg Rating: Descending</a>
      <a class="dropdown-item" id="pages-asc" href="?sort=pages&order=asc">Page Count: Ascending</a>
      <a class="dropdown-item" id="pages-desc" href="?sort=pages&order=desc">Page Count: Descending</a>
    </div>
  </div>
</div>
</div>

<div class="books" id="indiv-book-stats">
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <p id="carousel-header">Loading library...<br><br><br></p>
      </div>
      <% @books.each do |book| %>
        <div class="carousel-item">
          <div class="book-<%= book.id %>" id="book-<%= book.id %>">
            <h2 class="book-title"><%= link_to book.title, book_path(book.id) %></h2>
            <img src="<%= book.img %>">
            <h3><%= book.average_review_score.round %> <i class="fas fa-star"></i></h3>
            <h3><%= book.total_reviews %> reviews</h3>
            by:<% book.authors.each do |author| %>
            <h2 class="author-name"><%= link_to author.name, author_path(author.id) %></h2>
            <% end %>
            <p><%=  book.pages %> pages</p>
            <p>Published in: <%=  book.published_year %></p>
          </div>
        </div>
      <% end %>
    </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true" ></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  </div>
</div>

app/views/books/new.html.erb
<head>
  <title>Add Book</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="/stylesheets/new_book.css">
</head>
<body>
  <div class="jumbotron">
    <h1>Enter your new book below:</h1>
    <%= form_for @book do |f| %>
      <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

          <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    <%= f.label :What_is_it_called? %> <br>
    <%= f.text_field :title %> <br>
    <%= f.label :How_many_pages_does_it_have? %> <br>
    <%= f.number_field :pages %> <br>
    <%= f.label :When_was_it_published? %> <br>
    <%= f.number_field :published_year %> <br>
      <%= f.label :Who_wrote_it? %> <br>
      <%= f.text_field :authors, value: ' ' %> <br><br><br>
    <%= f.submit %>
  <% end %>
  </div>
</body>

app/views/books/show.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="/stylesheets/book_show.css">
</head>
<body>


  <div id="book-information">
<h1>"<%= @book.title %>"</h1>
<div class="buttonz"><%= link_to "Add Review", new_book_review_path(@book) %></div>
<div class="buttonz"><%= link_to "Delete Book", book_path(@book), method: :delete %></div>
<br><br>Author(s):
<% @book.authors.each do |author| %>
  <h2 class="author-name"><%= link_to author.name, author_path(author.id) %></h2>
<% end %>
<img src="<%= @book.img %>"><br>
<%= @book.pages %> pages <br>
Published in <%= @book.published_year %><br>
Average rating: <%= @book.average_review_score.round %><i class="fas fa-star"></i>
</div>


<article class="book-stats">
  <ul>
  <li><div class="top-books">

    <h2>Top ratings for this book:</h2>

      <% @book.top_three_reviews.each do |review| %>
        "<%= review.title %>"<br>
        by <%= link_to review.user_name(review.user_id), user_path(review.user_id) %>
        , who rated it <%= review.rating %><i class="fas fa-star"></i><br>
      <% end %>
  </div></li>
  <li><div class="lowest-books">
    <h2>Lowest ratings for this book:</h2>
      <% @book.bottom_three_reviews.each do |review| %>
      "<%= review.title %>"<br>
      by <%= link_to review.user_name(review.user_id), user_path(review.user_id) %>
      , who rated it <%= review.rating %><i class="fas fa-star"></i><br>
      <% end %>
  </div></li>
</ul>
</article>

<div id="book-reviews">
  <h2>All reviews</h2>
  <div class="container">
    <div class="row">
      <% @book.reviews.each do |review| %>
      <div class="col-4 ">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">"<%= review.title %>"</h5>
            <p class="card-text"><%= review.rating %><i class="fas fa-star"></i></p>
            <p class="card-text"><%= link_to review.user_name(review.user_id), user_path(review.user_id) %></p>
            <p class="card-text">"<%= review.description %>"</p>
            <p class="card-text">submitted <%= review.created_at.strftime("%B %d, %Y") %></p><br><br>
          </div>
        </div>
      </div>
      <% end %>
      </div>
    </div>
  </div>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClub</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" type="text/css" href="stylesheets/normalize.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href='//fonts.googleapis.com/css?family=Arizonia' rel='stylesheet' type='text/css'>
    <link href="//fonts.googleapis.com/css?family=Cinzel" rel="stylesheet" type='text/css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/stylesheets/main.css">
  </head>
  <body>
    <nav id="nav-bar">
      <ul>
        <li><a title="home-link" id="home-link" href="/">home</a></li>
        <li><a title="index-link" id="index-link" href="/books">browse all books</a></li>
      </ul>
    </nav>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reviews/new.html.erb
<head>
  <title>Add Review</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="/stylesheets/new_book.css">
  <link rel="stylesheet" type="text/css" href="/stylesheets/new_review.css">
</head>
<body>
  <div class="jumbotron">
    <h1>Enter Your Review Below:</h1>
    <%= form_for [@book, @review] do |f| %>
      <% if @review.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
          <ul>
          <% @review.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    <div id='review-form'>
      <div id='inner-review-form'>
        <%= f.label :title %> <br>
        <%= f.text_field :title %> <br>
        <%= f.label :user %><br>
        <%= f.text_field :user %><br>
        <%= f.label :rating %> <br>
        <%= f.number_field :rating, in: 1..5%> <br>
        <%= f.label :description %> <br>
        <%= f.text_field :description %> <br>
      </div>
      <div id='submit-button'>
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</body>

app/views/users/show.html.erb
<head>
  <title>Add Book</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="/stylesheets/user_show.css">
</head>
<div class="title" >
  <h1>their reviews</h1>
</div>
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Sort by:
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" id="review-date-desc" href="?sort=reviewsdate&order=desc">Reviews: Newest First</a>
    <a class="dropdown-item" id="review-date-asc" href="?sort=reviewsdate&order=asc">Reviews: Oldest First</a>
  </div>
</div>
<div class="card">
  <div class="card-body">
    <h2><%= @user.name %></h2>
    <h5 class="card-title">Profile</h5>
    <p class="card-text">Contribution: <%= @reviews.count %> review(s)</p>
    <p class="card-text">Member since: <%= @user.created_at.strftime("%B %Y") %></p>
  </div>
</div>


<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <h1>Scroll to view this user's reviews</h1><br><br><br><br><br><br><br>
    </div>
      <div class="user-reviews">
        <% @reviews.each do |review| %>
        <div class="carousel-item">
          <div id="review-<%= review.id %>">
            <h2>"<%= review.title %>"</h2>
            <p>Book: <%= link_to review.book.title, book_path(review.book.id) %></p>
            <h2><%= review.rating %><i class="fas fa-star"></i></h2><br />
            <p>"<%= review.description %>" </p><br>
            <p class="submitted-on">submitted <%= review.created_at.strftime("%B %d, %Y") %></p>
            <%= link_to "Delete Review", review_path(review), method: :delete %>
          </div>
        </div>
        <% end %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/welcome/index.html.erb
<head>
  <title>Home</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="stylesheets/welcome.css">
</head>
<body>
  <div class="jumbotron">
    <svg class="right">
      <line x1="" y1="0" x2="250" y2="0" style="stroke:rgb(255,255,255);stroke-width:5" />
    </svg>
    <svg class="left">
      <line x1="" y1="0" x2="250" y2="0" style="stroke:rgb(255,255,255);stroke-width:5" />
    </svg>
    <div class="container">
      <h1>Clampett, Taylor & Frey</h1>
      <p>A virtual book club</p>
    </div>
  </div>
</body>